name: DEV deployment

on:
  push:
    branches: [main]

env:
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform_init:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: env/dev
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan   
      
  approval:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: env/dev
    needs: terraform_init
    steps:
      - name: Manual approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: nebojsamilosav
          minimum-approvals: 1  
          issue-title: "Approve Terraform Apply"
          secret: ${{ github.TOKEN }}

  terraform_apply:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      issues: write
    needs: approval
    defaults:
      run:
        working-directory: env/dev
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Run Apply
        run: echo "Waiting for Approval to proceed"
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply --auto-approve       